// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypkkmypzugcynjmfeyus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwa2tteXB6dWdjeW5qbWZleXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDM3MzEsImV4cCI6MjA2NTM3OTczMX0.boTb0R2t8ixFLx99LiPe73M9mkIEdd81k1NeSrbTH1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);